spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 1614969957
    url: jdbc:mysql://139.159.149.164:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: rabbitmq
    password: rabbitmq
    host: 139.159.149.164
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 139.159.149.164
    database: 0
    port: 8092
    password: 1614969957
  cache:
    cache-names: menus_cache
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://139.159.149.164:8097/
debug: true

# 分页配置参数


# 一些自定义配置
custom:
  config:
#    # 需要做卷映射 (docker 映射到本地)
#    docker_database_path: /var/log/mysql
#    # 数据库服务器备份路径
#    server_database_path: E:\todo_files\docker\mysql80\log
#    # docker镜像名字
#    docker_name: mysql80
    # 数据库备份过期时间（秒）
    backup_expire: 7200

#xxl:
#  job:
#    admin:
#      addresses: http://127.0.0.1:8090/xxl-job-admin  #xxljob调度中心部署  例如：http://127.0.0.1:8080/xxl-job-admin
#    executor:
#      appname: testJob #xxljob配置的执行器名称，
#      ip:             #执行器IP，默认为空表示自动获取IP
#      port: 9999 #xxljob配置的端口号，默认为9999
#      logpath: /data/xxl-job/jobhandler  #执行器运行日志文件存储磁盘路径
#      logretentiondays: -1  #调度中心日志表数据保存天数，过期日志自动清理；限制大于等于7时生效，否则, 如-1，关闭自动清理功能
#    accessToken: #调度中心通讯TOKEN [选填]：非空时启用